data:
  root: ../dataset/birdclef-2024
  metadata_csv: ../dataset/birdclef-2024/train_metadata.csv
  audio_subdir: train_audio
  splits_dir: ../dataset/splits
  labels_json: ../dataset/labels.json
audio:
  sample_rate: 32000
  frame_sec: 1.0
  hop_sec: 0.5
  n_mels: 128
  fmin: 50
  fmax: 14000
train:
  epochs: 20
  batch_size: 128
  lr: 0.001
  weight_decay: 0.0001
  mix_prob: 0.5
  mix_snr_db: 3.0
  num_workers: 2
  val_every: 1
  seed: 42
model:
  cnn_width: 64
  dropout: 0.2
inference:
  threshold: 0.5
  min_duration_sec: 0.6
  merge_gap_sec: 0.3
  hysteresis_low: 0.45
  hysteresis_high: 0.55
outputs:
  dir: ./outputs
  checkpoints: ./outputs/checkpoints
  preprocessed: ./outputs/preprocessed  # Directory for preprocessed files
